# Generated by Django 4.1 on 2022-11-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tourism',
        ),
    ]
